/* eslint-disable react/no-unescaped-entities */
import Layout from "./layout";
import { ContentDescription, ContentHeader, ListItem, PrivacyWrapper, Span } from "./styles";
import { MobileH1M, MobileH3SM } from "@/utils/typography";

function Privacy() {
  return (
    <Layout>
    <PrivacyWrapper>
      <MobileH3SM>PRIVACY POLICY</MobileH3SM>
      <br />
      <br />
      <ContentDescription>Last updated: March 20, 2025</ContentDescription>
      <ContentDescription>
        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when
        You use the Service and tells You about Your privacy rights and how the law protects You.
      </ContentDescription>
      <ContentDescription>
        We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of
        information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy
        Policy Generator.
      </ContentDescription>

      <ContentHeader>Interpretation and Definitions</ContentHeader>
      <MobileH1M>Interpretation</MobileH1M>
      <ContentDescription>
        The words of which the initial letter is capitalized have meanings defined under the following conditions. The following
        definitions shall have the same meaning regardless of whether they appear in singular or in plural.
        <br />
      </ContentDescription>

      <MobileH1M>Definitions</MobileH1M>
      <ContentDescription>For the purposes of this Privacy Policy:</ContentDescription>
      <ContentDescription>
        <ListItem>
          <Span>Account</Span> means a unique account created for You to access our Service or parts of our Service.
        </ListItem>
        <ListItem>
          <Span>Affiliate</Span> means an entity that controls, is controlled by, or is under common control with a party, where
          &quot;control&quot; means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote
          for election of directors or other managing authority.
        </ListItem>
        <ListItem>
          <Span>Application</Span> refers to 1159realty web app, the software program provided by the Company.
        </ListItem>
        <ListItem>
          <Span>Company</Span> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to 1159realty
          Nig. Ltd, No. 23, Offa Road, Opposite Kwara State Registry, Ilorin.
        </ListItem>
        <ListItem>
          <Span>Country</Span> refers to: Nigeria.
        </ListItem>
        <ListItem>
          <Span>Device</Span> means any device that can access the Service such as a computer, a cellphone, or a digital tablet.
        </ListItem>
        <ListItem>
          <Span>Personal Data</Span> is any information that relates to an identified or identifiable individual.
        </ListItem>
        <ListItem>
          <Span>Service</Span> refers to the Application.
        </ListItem>
        <ListItem>
          <Span>Service Provider</Span> means any natural or legal person who processes the data on behalf of the Company. It
          refers to third-party companies or individuals employed by the Company to facilitate the Service, provide the Service on
          behalf of the Company, perform services related to the Service, or assist the Company in analyzing how the Service is
          used.
        </ListItem>
        <ListItem>
          <Span>Usage Data</Span> refers to data collected automatically, either generated by the use of the Service or from the
          Service infrastructure itself (for example, the duration of a page visit).
        </ListItem>
        <ListItem>
          <Span>You</Span> means the individual accessing or using the Service, or the company, or other legal entity on behalf of
          which such individual is accessing or using the Service, as applicable.
        </ListItem>
      </ContentDescription>
      <br />

      <ContentHeader>Collecting and Using Your Personal Data</ContentHeader>
      <br />
      <MobileH1M>Types of Data Collected</MobileH1M>
      <br />
      <br />
      <MobileH1M>Personal Data</MobileH1M>

      <ContentDescription>
        While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to
        contact or identify You. Personally identifiable information may include, but is not limited to:
      </ContentDescription>
      <ContentDescription>
        <ListItem>Email address</ListItem>
        <ListItem>First name and last name</ListItem>
        <ListItem>Phone number</ListItem>
        <ListItem>Address, State, Province, ZIP/Postal code, City</ListItem>
        <ListItem>Usage Data</ListItem>
        <br />
      </ContentDescription>

      <MobileH1M>Usage Data</MobileH1M>

      <ContentDescription>
        Usage Data is collected automatically when using the Service. <br />
        Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type,
        browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages,
        unique device identifiers and other diagnostic data. <br />
        When You access the Service by or through a mobile device, We may collect certain information automatically, including,
        but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device,
        Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic
        data. <br />
        We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by
        or through a mobile device.
        <br />
      </ContentDescription>
      <br />
      <MobileH1M>Use of Your Personal Data</MobileH1M>

      <ContentDescription>
        The Company may use Personal Data for the following purposes: <br />
      </ContentDescription>
      <ContentDescription>
        <ListItem>
          <Span>To provide and maintain our Service,</Span> including to monitor the usage of our Service.
        </ListItem>
        <ListItem>
          <Span>To manage Your Account:</Span> to manage Your registration as a user of the Service. The Personal Data You provide
          can give You access to different functionalities of the Service that are available to You as a registered user.
        </ListItem>
        <ListItem>
          <Span>For the performance of a contract:</Span> the development, compliance, and undertaking of the purchase contract
          for the products, items, or services You have purchased or of any other contract with Us through the Service.
        </ListItem>
        <ListItem>
          <Span>To contact You:</Span> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic
          communication, such as a mobile application's push notifications regarding updates or informative communications related
          to the functionalities, products, or contracted services, including security updates, when necessary or reasonable for
          their implementation.
        </ListItem>
        <ListItem>
          <Span>To provide You</Span> with news, special offers, and general information about other goods, services, and events
          we offer that are similar to those that you have already purchased or enquired about unless You have opted not to
          receive such information.
        </ListItem>
        <ListItem>
          <Span>To manage Your requests:</Span> To attend and manage Your requests to Us.
        </ListItem>
        <ListItem>
          <Span>For business transfers:</Span> We may use Your information to evaluate or conduct a merger, divestiture,
          restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going
          concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our
          Service users is among the assets transferred.
        </ListItem>
        <ListItem>
          <Span>For other purposes:</Span> We may use Your information for other purposes, such as data analysis, identifying
          usage trends, determining the effectiveness of our promotional campaigns, and evaluating and improving our Service,
          products, services, marketing, and your experience.
        </ListItem>
        <br />
        We may share Your personal information in the following situations:
        <br />
        <br />
        <ListItem>
          <Span>With Service Providers:</Span> We may share Your personal information with Service Providers to monitor and
          analyze the use of our Service, to contact You.
        </ListItem>
        <ListItem>
          <Span>For business transfers:</Span> We may share or transfer Your personal information in connection with, or during
          negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to
          another company.
        </ListItem>
        <ListItem>
          <Span>With Affiliates:</Span> We may share Your information with Our affiliates, in which case we will require those
          affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture
          partners, or other companies that We control or that are under common control with Us.
        </ListItem>
        <ListItem>
          <Span>With business partners:</Span> We may share Your information with Our business partners to offer You certain
          products, services, or promotions.
        </ListItem>
        <ListItem>
          <Span>With other users:</Span> When You share personal information or otherwise interact in the public areas with other
          users, such information may be viewed by all users and may be publicly distributed outside.
        </ListItem>
        <ListItem>
          <Span>With Your consent:</Span> We may disclose Your personal information for any other purpose with Your consent.
        </ListItem>
      </ContentDescription>
      <br />
      <MobileH1M>Retention of Your Personal Data</MobileH1M>
      <ContentDescription>
        The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy
        Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for
        example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal
        agreements and policies.
        <br />
        <br />
        The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter
        period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service,
        or We are legally obligated to retain this data for longer time periods.
      </ContentDescription>

      <br />
      <MobileH1M>Transfer of Your Personal Data</MobileH1M>
      <ContentDescription>
        Your information, including Personal Data, is processed at the Company's operating offices and in any other places where
        the parties involved in the processing are located. It means that this information may be transferred to — and maintained
        on — computers located outside of Your state, province, country or other governmental jurisdiction where the data
        protection laws may differ than those from Your jurisdiction.
        <br />
        <br />
        Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that
        transfer.
        <br />
        <br />
        The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with
        this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are
        adequate controls in place including the security of Your data and other personal information.
      </ContentDescription>

      <br />
      <MobileH1M>Delete Your Personal Data</MobileH1M>
      <ContentDescription>
        You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
        <br />
        <br />
        Our Service may give You the ability to delete certain information about You from within the Service
        <br />
        <br />
        You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting
        the account settings section that allows you to manage Your personal information. You may also contact Us to request
        access to, correct, or delete any personal information that You have provided to Us.
        <br />
        <br />
        Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do
        so.
      </ContentDescription>
      <br />
      <ContentHeader>Disclosure of Your Personal Data</ContentHeader>
      <MobileH1M>Business Transactions</MobileH1M>
      <ContentDescription>
        If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide
        notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
      </ContentDescription>
      <br />

      <MobileH1M>Law enforcements</MobileH1M>
      <ContentDescription>
        Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in
        response to valid requests by public authorities (e.g. a court or a government agency).
      </ContentDescription>
      <br />

      <MobileH1M>Other legal requirements</MobileH1M>
      <ContentDescription>
        The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
        <br />
        <ListItem>Comply with a legal obligation</ListItem>
        <ListItem>Protect and defend the rights or property of the Company</ListItem>
        <ListItem>Prevent or investigate possible wrongdoing in connection with the Service</ListItem>
        <ListItem>Protect the personal safety of Users of the Service or the public</ListItem>
        <ListItem>Protect against legal liability</ListItem>
      </ContentDescription>
      <br />

      <MobileH1M>Security of Your Personal Data</MobileH1M>
      <ContentDescription>
        The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or
        method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal
        Data, We cannot guarantee its absolute security
      </ContentDescription>
      <br />

      <MobileH1M>Children&apos;s Privacy</MobileH1M>
      <ContentDescription>
        Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information
        from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with
        Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13
        without verification of parental consent, We take steps to remove that information from Our servers.
        <br />
        If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a
        parent, We may require Your parent&apos;s consent before We collect and use that information.
      </ContentDescription>

      <br />
      <MobileH1M>Links to Other Websites</MobileH1M>
      <ContentDescription>
        Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will
        be directed to that third party&apos;s site. We strongly advise You to review the Privacy Policy of every site You visit.
        <br />
        We have no control over and assume no responsibility for the content, privacy policies or practices of any third party
        sites or services.
      </ContentDescription>
      <br />

      <MobileH1M>Changes to this Privacy Policy</MobileH1M>
      <ContentDescription>
        We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on
        this page
        <br />
        We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update
        the "Last updated" date at the top of this Privacy Policy.
        <br />
        You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective
        when they are posted on this page.
      </ContentDescription>
      <br />
      <MobileH1M>Contact Us</MobileH1M>
      <ContentDescription>
        If you have any questions about this Privacy Policy, You can contact us:
        <br />
        <br />
        By email:<a href="mailto:admin@1159realty.com"> admin@1159realty.com</a>
        <br />
        By phone number:<a href="tel:+2348061747003"> 08061747003</a>
      </ContentDescription>
    </PrivacyWrapper>
    </Layout>
  );
}

export { Privacy };
