import type { Metadata, Viewport } from "next";

import "../styles/globals.css";

import { AppWrapper } from "@/components/appWrapper";

// TODO: Add metadata
// TODO: Update the viewport metadata
export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppWrapper>{children}</AppWrapper>
      </body>
    </html>
  );
}
